# Generated by Django 3.0.3 on 2020-04-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('registrationDate', models.DateTimeField(verbose_name='date registered')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=300)),
                ('numPPE', models.IntegerField(default=0)),
                ('typePPE', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('delivDate', models.DateTimeField(verbose_name='date for delivery')),
                ('orderDate', models.DateTimeField(verbose_name='date ordered')),
                ('notes', models.CharField(max_length=4000)),
            ],
        ),
    ]
