# Generated by Django 3.0.3 on 2020-04-16 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='fName',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='lName',
        ),
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='donor',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='donor',
            name='zipcode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
