# Generated by Django 3.0.3 on 2020-04-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200416_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('numPPE', models.IntegerField(default=0)),
                ('typePPE', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=100)),
                ('zipCode', models.CharField(max_length=10)),
                ('delivDate', models.DateTimeField(verbose_name='date for delivery')),
                ('orderDate', models.DateTimeField(verbose_name='date ordered')),
                ('notes', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='zipcode',
            new_name='zipCode',
        ),
    ]
