# Generated by Django 3.0.3 on 2020-04-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200418_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='delivDate',
            field=models.DateField(verbose_name='date for delivery'),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='orderDate',
            field=models.DateField(verbose_name='date ordered'),
        ),
    ]
