# Generated by Django 3.0.3 on 2020-04-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_requestmodel_idnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
