# Generated by Django 3.0.3 on 2020-04-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_requestmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
