# Generated by Django 3.0.3 on 2020-04-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200419_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestmodel',
            old_name='idNum',
            new_name='primary_key',
        ),
    ]
