# Generated by Django 3.0.3 on 2020-04-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200420_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='city',
            field=models.CharField(default='San Diego', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
