# Generated by Django 3.0.2 on 2020-04-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200420_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='typeHandle',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
