# Generated by Django 3.0.2 on 2020-05-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_requestmodel_typehandle'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='organization',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
