# Generated by Django 3.0.2 on 2020-05-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_requestmodel_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
