# Generated by Django 3.0.2 on 2020-05-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200503_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='phone',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
